### ISSUE TITLE
錯誤的路徑設置

### ISSUE THREAD

**Issue by ray1422** [ECPay/OpenCart2.3_Logistics#1]
下面這行在某些環境下會導向錯誤的路徑，請修改成

$al_srvreply = (($_SERVER['HTTPS']) ? "https" : "http") . '://' . $_SERVER['HTTP_HOST'] . $_SERVER['PHP_SELF'] . '?route=extension/shipping/ecpaylogistic/set_store_info';

https://github.com/ECPay/OpenCart2.3_Logistics/blob/98b08cb826363c30400b2fcb6e52f73efbffd7ff/upload/catalog/controller/extension/shipping/ecpaylogistic.php#L50

**Comment by AllennChang** [comment]
你好, 請跟我們技術客服團隊連絡,將安排專員協助服務您的問題, 請寄信到 techsupport@ecpay.com.tw ,再麻煩囉
